name: ABI Checks

on: [push, pull_request]

jobs:
  abicheck:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
          ref: 'v2.11.0'
          path: old

    - uses: actions/checkout@v3
      with:
          path: current

    - name: install abidiff
      run: sudo apt-get update && sudo apt-get install -y abigail-tools

    - name: make shared lib
      run: |
        cmake -S old -B old/build && cmake --build old/build

    - name: make current shared lib
      run: |
        cmake -S current -B current/build && cmake --build current/build

    - name: abidiff compare
      id: abidiff
      run: abidiff old/libre.so current/libre.so
      continue-on-error: true

    - name: display warning
      if: steps.abidiff.outcome != 'success'
      run: echo "::warning::ABI Check failed - bump ABI version"
