name: Build

on: [push, pull_request]

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        compiler: [gcc, clang]
        os: [ubuntu-18.04, ubuntu-20.04, macos-latest]
        exclude:
           - os: macos-latest
             compiler: gcc
    env:
      CC: ${{ matrix.compiler }}

    steps:
    - uses: actions/checkout@v2

    - name: install macOS homebrew packages
      if: ${{ runner.os == 'macOS' }}
      run: |
        brew install openssl@1.1
        rm -f /usr/local/opt/openssl
        ln -s /usr/local/Cellar/openssl@1.1/1.1.1m /usr/local/opt/openssl

    - name: make info
      run: |
        echo "OS: ${{ matrix.os }}"
        echo "--- ${{ matrix.compiler }} DEBUG VERSION ---"
        ${{ matrix.compiler }} - --version
        echo "--- make info ---"
        make info

    - name: test re.mk
      run: make -C mk -f test.mk

    - name: make
      run: make EXTRA_CFLAGS=-Werror CCACHE=

    - uses: sreimers/pr-dependency-action@v0.3
      with:
        name: rem
        repo: https://github.com/baresip/rem
        secret: ${{ secrets.GITHUB_TOKEN }}
        working-directory: '../.'

    - uses: sreimers/pr-dependency-action@v0.3
      with:
        name: retest
        repo: https://github.com/baresip/retest.git
        secret: ${{ secrets.GITHUB_TOKEN }}
        working-directory: '../.'

    - name: retest
      run: |
        cd ..
        rm re/libre.so || true
        rm re/libre.dylib || true
        make -C rem librem.a
        cd retest && make && ./retest -r
