name: ccheck

on: [push, pull_request]

jobs:
  ccheck:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: ccheck
      run: |
        wget "https://raw.githubusercontent.com/baresip/baresip/main/test/ccheck.py"
        python3 ccheck.py
