name: Coverage

on: [push, pull_request]

jobs:
  coverage:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: make
      run: | 
        make EXTRA_CFLAGS="--coverage" CCACHE=

    - uses: sreimers/pr-dependency-action@v0.3
      with:
        name: rem
        repo: https://github.com/baresip/rem
        secret: ${{ secrets.GITHUB_TOKEN }}
        working-directory: '../.'

    - uses: sreimers/pr-dependency-action@v0.3
      with:
        name: retest
        repo: https://github.com/baresip/retest.git
        secret: ${{ secrets.GITHUB_TOKEN }}
        working-directory: '../.'

    - name: retest
      run: |
        cd ..
        rm re/libre.so || true
        rm re/libre.dylib || true
        make -C rem librem.a
        cd retest; cmake -B build -DCMAKE_EXE_LINKER_FLAGS="--coverage" && \
          cmake --build build -j && ./retest -a

    - name: gcov
      run: | 
        cd ../re
        gcov build-x86_64/**/*.o

    - name: install gcovr
      run: |
        pip install gcovr==5.0

    - name: coverage check
      run: |
        min_cov="57.7"
        cov=$(~/.local/bin/gcovr -r . -s | grep lines | awk '{ print $2 }' | sed 's/%//')
        echo "Coverage: ${cov}% (min $min_cov%)"
        exit $(echo "$cov < $min_cov" | bc -l)
