name: valgrind leak check

on: [push, pull_request]

jobs:
  valgrind:
    runs-on: ubuntu-latest 

    steps:
    - uses: actions/checkout@v2

    - name: install packages
      run: |
        sudo apt-get update && sudo apt-get install -y libssl-dev valgrind

    - name: make
      run: make EXTRA_CFLAGS=-Werror CCACHE=

    - uses: sreimers/pr-dependency-action@main
      with:
        name: rem
        repo: https://github.com/baresip/rem
        secret: ${{ secrets.GITHUB_TOKEN }}
        working-directory: '../.'

    - uses: sreimers/pr-dependency-action@main
      with:
        name: retest
        repo: https://github.com/baresip/retest
        secret: ${{ secrets.GITHUB_TOKEN }}
        working-directory: '../.'

    - name: retest
      run: |
        cd ..
        rm re/libre.so || true
        rm re/libre.dylib || true
        make -C rem librem.a
        cd retest
        make
        valgrind --leak-check=full --show-reachable=yes --error-exitcode=42 ./retest -r
